# config\app.yaml

name: Run Maven tests  # 👈 numele workflow-ului (scope global)

env: "development"

service:
  name: "jsonplaceholder-api"
  baseUrl: "https://jsonplaceholder.typicode.com/"

timeouts:
  connectMs: 1000
  readMs: 3000
